[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "webgui-py"
version = "0.2.2"
description = "A simple Python GUI framework that uses HTML as the interface"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]

dependencies = [
	"flask",
	"pygame-ce"
]

[tool.setuptools.packages.find]
where = ["."]